"""
email_sender.py
Gmail SMTP email delivery for absent reports.

All configuration comes from settings.py (config.ini [smtp]).
Uses only the standard-library smtplib — no extra dependencies.
"""

import logging
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

_GMAIL_HOST = 'smtp.gmail.com'
_GMAIL_PORT = 587


# ─── Body builders ───────────────────────────────────────────────────────────

def _by_dept(absent: list) -> dict:
    """Group absent employees by department."""
    grouped: dict = {}
    for e in absent:
        dept = (e.get('dept') or 'Unknown').strip()
        grouped.setdefault(dept, []).append((e.get('name') or '').strip())
    return grouped


def build_plain_body(report_date: date, absent: list, summary: dict) -> str:
    """Return a plain-text email body for the absent report."""
    today_str  = report_date.strftime('%d/%m/%Y')
    total      = summary.get('total', 0)
    present    = summary.get('present_count', 0)
    absent_cnt = summary.get('absent_count', len(absent))

    lines = [
        f"Daily Absent Report — {today_str}",
        "=" * 42,
        f"Total: {total}   Present: {present}   Absent: {absent_cnt}",
        "",
        "Absent by Department",
        "-" * 42,
    ]

    grouped = _by_dept(absent)
    for dept in sorted(grouped):
        names = grouped[dept]
        lines.append(f"\n{dept} ({len(names)} absent):")
        for name in names:
            lines.append(f"  - {name}")

    lines.extend([
        "",
        "-" * 42,
        f"Generated by ZKTeco Attendance Bot on {date.today().strftime('%d/%m/%Y')}",
    ])
    return "\n".join(lines)


def build_html_body(report_date: date, absent: list, summary: dict) -> str:
    """Return an HTML email body for the absent report."""
    today_str  = report_date.strftime('%d/%m/%Y')
    total      = summary.get('total', 0)
    present    = summary.get('present_count', 0)
    absent_cnt = summary.get('absent_count', len(absent))

    dept_rows_html = ""
    grouped = _by_dept(absent)
    for dept in sorted(grouped):
        names     = grouped[dept]
        names_li  = "".join(f"<li>{n}</li>" for n in names)
        dept_rows_html += (
            f'<tr>'
            f'<td style="padding:8px 12px;vertical-align:top;font-weight:bold;'
            f'border:1px solid #ddd;">{dept} ({len(names)})</td>'
            f'<td style="padding:8px 12px;border:1px solid #ddd;">'
            f'<ul style="margin:0;padding-left:18px;">{names_li}</ul></td>'
            f'</tr>'
        )

    if not dept_rows_html:
        dept_rows_html = (
            '<tr><td colspan="2" style="padding:8px 12px;text-align:center;">'
            'No absences.</td></tr>'
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<title>Daily Absent Report — {today_str}</title></head>
<body style="font-family:Arial,sans-serif;color:#222;margin:0;padding:20px;background:#f9f9f9;">
  <div style="max-width:700px;margin:auto;background:#fff;border-radius:6px;
              box-shadow:0 2px 6px rgba(0,0,0,.12);overflow:hidden;">
    <div style="background:#c62828;padding:20px 24px;">
      <h1 style="margin:0;font-size:20px;color:#fff;">
        &#128203; Daily Absent Report &mdash; {today_str}
      </h1>
    </div>
    <div style="padding:20px 24px;">
      <table style="border-collapse:collapse;margin-bottom:20px;">
        <tr>
          <td style="padding:4px 20px 4px 0;font-size:15px;">
            <b>&#128101; Total:</b> {total}
          </td>
          <td style="padding:4px 20px 4px 0;font-size:15px;color:#2e7d32;">
            <b>&#9989; Present:</b> {present}
          </td>
          <td style="padding:4px 20px 4px 0;font-size:15px;color:#c62828;">
            <b>&#10060; Absent:</b> {absent_cnt}
          </td>
        </tr>
      </table>
      <table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr style="background:#c62828;color:#fff;">
            <th style="padding:10px 12px;text-align:left;border:1px solid #b71c1c;">
              Department
            </th>
            <th style="padding:10px 12px;text-align:left;border:1px solid #b71c1c;">
              Absent Employees
            </th>
          </tr>
        </thead>
        <tbody>
          {dept_rows_html}
        </tbody>
      </table>
    </div>
    <div style="padding:12px 24px;background:#f5f5f5;font-size:12px;color:#888;">
      Generated by ZKTeco Attendance Bot &bull; {date.today().strftime('%d/%m/%Y')}
    </div>
  </div>
</body>
</html>"""


# ─── Send function ────────────────────────────────────────────────────────────

def send_report_email(
    sender_email: str,
    sender_name: str,
    app_password: str,
    recipients: list,
    subject: str,
    report_date: date,
    absent: list,
    summary: dict,
    fmt: str = 'html',
) -> tuple:
    """
    Send the absent report by email via Gmail SMTP (TLS on port 587).

    Parameters
    ----------
    sender_email   Gmail address used as the sender.
    sender_name    Display name that appears in the From: header.
    app_password   Gmail App Password (not the account password).
    recipients     List of recipient email addresses.
    subject        Email subject; ``{date}`` is replaced with the report date.
    report_date    The date the report covers.
    absent         List of absent employee dicts from mdb_reader.
    summary        Summary dict (keys: total, present_count, absent_count, …).
    fmt            ``'html'`` | ``'plain'`` | ``'both'``

    Returns
    -------
    ``(True, '')`` on success, ``(False, error_message)`` on failure.
    """
    if not sender_email or not app_password:
        return False, 'SMTP not fully configured: sender email or app password missing.'
    if not recipients:
        return False, 'No recipients configured.'

    subject_str = subject.replace('{date}', report_date.strftime('%d/%m/%Y'))
    plain_body  = build_plain_body(report_date, absent, summary)
    html_body   = build_html_body(report_date, absent, summary)

    try:
        if fmt == 'plain':
            msg = MIMEText(plain_body, 'plain', 'utf-8')
        elif fmt == 'html':
            msg = MIMEText(html_body, 'html', 'utf-8')
        else:  # 'both' — multipart/alternative, plain first then html (RFC 2046)
            msg = MIMEMultipart('alternative')
            msg.attach(MIMEText(plain_body, 'plain', 'utf-8'))
            msg.attach(MIMEText(html_body,  'html',  'utf-8'))

        msg['Subject'] = subject_str
        msg['From']    = f'{sender_name} <{sender_email}>'
        msg['To']      = ', '.join(recipients)

        with smtplib.SMTP(_GMAIL_HOST, _GMAIL_PORT, timeout=30) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.ehlo()
            smtp.login(sender_email, app_password)
            smtp.sendmail(sender_email, recipients, msg.as_string())

        logger.info(
            f"Email report for {report_date} sent to {len(recipients)} recipient(s)."
        )
        return True, ''

    except smtplib.SMTPAuthenticationError:
        err = 'SMTP authentication failed. Check sender email and App Password.'
        logger.error(err)
        return False, err
    except smtplib.SMTPException as e:
        logger.error(f"SMTP error: {e}")
        return False, f'SMTP error: {e}'
    except OSError as e:
        logger.error(f"Network/connection error: {e}")
        return False, f'Connection error: {e}'
    except Exception as e:
        logger.error(f"Unexpected email error: {e}")
        return False, str(e)
